### ISSUE TITLE
Support of curl in paypalproexpress plugin

### ISSUE THREAD

**Issue by laoneo** [akeeba/akeebasubs#112]
Would be nice if there is an option to switch to curl in the paypalproexpress plugin. Because of security i have disabled it on my hosting. There was no error message which helped me to figure out what was the cause that the paypalproexpress didn't work as on my dev server. After I switched allow_url_fopen on it started to work.
Thanks for considering.

**Comment by nikosdion** [comment]
I will be blunt and unforgiving because you used the word "security". Since PHP 5.2.0 there's the [allow_url_include](http://php.net/manual/en/filesystem.configuration.php#ini.allow-url-include) option which lets you disable remote file inclusion WITHOUT disabling URL fopen. As a result, if you have disabled allow_url_fopen for "security" reasons you have no idea about the basics of PHP security.

So, no, I won't consider your request. You're a developer. I explained you why your server setup is broken. Just fix your server setup.

**Comment by laoneo** [comment]
Just thought it would make sense to offer such an option as in the paypalpaymentspro plugin. I'm surprised you know my security skills :-1:

**Comment by nikosdion** [comment]
Well, you insisted that you disabled allow_url_fopen for security reasons. It is well-known in the PHP community that since PHP 5.2.0 this is no longer necessary because allow_url_include was introduced, exactly for this reason. Akeeba Subscriptions requires PHP 5.3.4 or later. Not to mention that PHP 5.2.0 was released on November 2nd, 2006. So, I don't need to magically "know" anything as you implied. I'm not a psychic, I don't pretend to be a psychic and I don't want to be a psychic. **You** have told me that your security skills are at least 8 years 3 months and 2 days stale. Clear?

As for disabling URL fopen wrappers: there is absolutely no need to. The allow_url_fopen switch was added in PHP 4.0.4 (released December 19th, 2000) to provide a way to disable remote file inclusions which were used to hack servers running badly coded scripts without proper user input validation. Previously it was only possible to do that by recompiling PHP. For reasons which have to do with how PHP works internally this couldn't be improved until PHP 5.2.0. Since this point opening a URI and including a URI have been separated and controlled independently. If you disable allow_url_fopen you also get to disable ALL wrappers which cannot be worked around by using cURL (see [stream_wrapper_register](http://php.net/manual/en/function.stream-wrapper-register.php)). No server administrator on their right mind would disable URL fopen when they can simply disable URL includes.

This brings us to the question of whether it makes any sense to implement cURL alongside URL fopen wrappers for the PayPal plugins. The answer is no. There is no point adding a huge block of code which requires additional development, testing and maintenance for a developers' product. If this was an end user's product I might go there. But it's a developer's product and developers (should) know how to properly (re)configure their servers.

**Comment by laoneo** [comment]
It's all fine Nicolas. Don't worry all will be god. Need to move on. Have a good day.
