### ISSUE TITLE
[backend] coupon code added to subscription editing

### ISSUE THREAD

**Issue by raramuridesign** [akeeba/akeebasubs#116]
Hi all
This is not an issue, its more of an enhancement.

Has anyone added the coupon code field to the backend ?

Currently this is only on the front-end and we would like to know if this can be added to the backend.

Matthew

**Comment by nikosdion** [comment]
It doesn't make sense to have the coupon field in the back-end. Coupons are used to provide a discount. You need them in the front-end since you obviously can't trust your clients to edit the price they have to pay. In the back-end you can edit the price paid, so there's no need to use the coupon code.

**Comment by raramuridesign** [comment]
The issue is as follows
The users dont enter code correctly, so the client is amending this in the backend.
The reason for the code in the backend is so the usage can be tracked. 

Is this difficult to integrate ?

**Comment by nikosdion** [comment]
Doesn't make any sense at all. The user has already paid full price and the corresponding tax. You can give him a discount if you feel magnanimous, but this DOES NOT mean that he used a coupon code. Moreover, you should add a note in the record, otherwise you'll have to wonder WTF I see this guy using the 20% coupon code having paid full price and then us giving him a 20% refund and we forgot to update our tax records and now we have committed a tax offense.

So, no, seriously, I won't implement this. It's a lousy idea.
