### ISSUE TITLE
Spaces in Username

### ISSUE THREAD

**Issue by caseyzman** [akeeba/akeebasubs#154]
Has this issue been fixed?
https://github.com/akeeba/akeebasubs/issues/38

It appears from the commit that it had been fixed, although I have the current version and I am still able to subscribe using spaces in my username.

**Comment by nikosdion** [comment]
I finished writing the Unit Test for the username validation a few seconds ago. I did test with usernames containing spaces and they are accepted just fine. Since I'm not sure which "current version" you are using (the "current version" is the one in the development branch and I'm pretty sure you're not using it) I can't help much with it.

If you're using Akeeba Subscriptions 3 or 4 your guess is as good as mine. The code in the AkeebasubsModelSubscribes is a stinking mess. I know because it took me the better part of last weekend to finally refactor. If you're talking about Akeeba Subscriptions 5 it's still work in progress and I can only tell you what is going on in the development branch: we do allow usernames with spaces.

**Comment by caseyzman** [comment]
Hello,

I should have been more specific. I meant I was using this version that I just downloaded: https://www.akeebabackup.com/download/akeeba-subscriptions/4-2-1.html

I had found this older post with a Github link for the Joomla tracker. It looks like the option was temporarily removed and spaces are now allowed?

http://forum.joomla.org/viewtopic.php?f=708&t=828343
https://github.com/joomla/joomla-cms/pull/2524

Thanks again for the quick response!

**Comment by nikosdion** [comment]
Well, that's Akeeba Subscriptions 4. Maybe it doesn't work. As I said, the code was a stinking mess. Debugging it is nearly impossible. That's why I had to refactor it for Akeeba Subscriptions 5. So, if you're saying it doesn't work it's very likely that it indeed doesn't work. See what I mean? Code is a mess, code is untestable, no idea if it works ==(lots of hard work)==> code is rewritten to be cleaner, code is tested, we know it does work.
