### ISSUE TITLE
PayPal update to SHA 256

### ISSUE THREAD

**Issue by tassosm** [akeeba/akeebasubs#191]
Our client received a notification from PayPal regarding 2 upgrades to their Payflow services. In the email it states that Paypal:

1 - Discontinue use of the Verisign G2 Root Certificate "PayPal will no longer accept secure connections to the API/IPN endpoints that are expecting our certificate/trust chain to be signed by the G2 Root Certificate. Only secure connection requests that are expecting our certificate/trust chain to be signed by the G5 Root Certificate will result in successful secure connections."

2 - Update to the SHA 256 signing algorithm. PayPal is upgrading SSL certificates on all Live and Sandbox endpoints from SHA-1 to the stronger and more robust SHA-256 in mid-2016.

Does it affect version 4.2.1 or 5.0 ?

**Comment by nikosdion** [comment]
No, it should have no difference. All you need to do is make sure that your server runs on OpenSSL (libssl) 1.0.1 or later.

*IMPORTANT!!!* SSL certificates signed with SHA-256 will NOT work with OpenSSL 0.9.x, including OpenSSL 0.9.8 included in the previous generation LTS versions of most Linux distributions. As a rule of thumb, if you can install updates of our Professional software on your server (delivered through our own site which uses an SHA-256 signed EV SSL certificate, NOT the Core versions which are delivered over plain HTTP) your server is most likely ready for this change.

**Comment by tassosm** [comment]
Either they have an SSL certificate or not. Right?

**Comment by nikosdion** [comment]
I think you need to read this https://blog.mozilla.org/security/2014/09/23/phasing-out-certificates-with-sha-1-based-signature-algorithms/  Follow the links in the article to understand more about the SSL certificate signatures and the security issues mitigated with the switch to SHA-256 signed certificates.

Also note that the Verisign G2 root only supports SHA-1 signatures, whereas the Verisign G5 root supports SHA-256 signatures. That's why PayPal is switching its SSL certificate to the new root. SSL certificate validation is handled transparently by libcurl and libssl on your server. See http://unitstep.net/blog/2009/05/05/using-curl-in-php-to-access-https-ssltls-protected-sites/ and read the "Proper fix" section. This is pretty much what Joomla! (and FOF and every self-respecting PHP software out there) does.

**Comment by tassosm** [comment]
OK got it. Thank you!
