### ISSUE TITLE
Suggestion. Do not run  "System - Akeeba Subscriptions Logout user" on a user sign up

### ISSUE THREAD

**Issue by gruz** [akeeba/akeebasubs#214]
When the plugin is enabled, after I finish a subscription process, I seem to be logged in
<a href="http://view.xscreenshot.com/e3762d8789e935afef861f72afc0808c" rel="group[xscreenshot]"  class="jcepopup"><img width="300" src="http://static.xscreenshot.com/2015/10/22/15/screen_e3762d8789e935afef861f72afc0808c"></a>

<a href="http://view.xscreenshot.com/f8a59b95f7a9b32602f88581d3440e26" rel="group[xscreenshot]"  class="jcepopup"><img width="300" src="http://static.xscreenshot.com/2015/10/22/15/screen_f8a59b95f7a9b32602f88581d3440e26"></a>

But if I try to browse the web-site - I'm thrown out. So it'd be logical either to redirect me to the login screen immediately, or not to logout me on first sign up.

**Comment by nikosdion** [comment]
Based on your last two issues I have concluded that:
* you don't read the documentation
* you cannot think, e.g. the Logout user plugin indeed logs out the user, why would that be required, maybe I should read the fine manual.
* you are not a developer since every issue you come up with is not only baseless but also doesn't withstand a cursory reading of the code
* you do not know how Joomla! works e.g. how ACL works – which explains why you need to log out the user after subscribing (otherwise the ACL privileges wouldn't be applied, HELLO THERE!!!!!)
* you don't know how to use Joomla!, e.g. disabling a system plugin

This repository is for developers and the issues are meant for code issues, submitted and fixed by actual developers who know PHP. It's not meant to have me teach you how Joomla! works or generic support. Any further issue filed from you will be closed and locked without a response. Please do not bother filing another issue.

**Comment by nikosdion** [comment]
Thank you for the hate email you just sent me. I'm glad to know that you consider calling me someone who enjoys anal sex to be a derogatory term in your pea-sized brain. You are not only an idiot who can't read the plugin name, the plugin description and the documentation but also a massively ignorant bigot.

As for the technical aspect of this NON-ISSUE, you have to think about two very simple things that you are obviously incapable of considering given the tiny size of your brain and the fact that it's fully occupied by your bigotry.

First of all, the return URL can be accessed by everyone. This is necessary since it's a *return URL*. Like, you are a guest, enter your desired user information in the form, hit Subscribe Now and taken to a site to perform the payment. Then you *return* to that URL. You are not logged in. In fact, the user account has _just_ been activated. So the system logs you in when you access this URL. If you remained logged in anyone who could guess or read your subscription ID (not that hard to guess, huh?) could log in to the site. Massive security issue. The solution is to log out the user *unless* they were logged in *before* coming to this page. A cursory examination of `Akeeba\Subscriptions\Site\Controller\Message` can tell you that. There are comments for a reason.

As for the existence of the plugin itself, let's first read its description, OK? "Logs out the current user if requested by Akeeba Subscription in order to refresh his Joomla permissions". It should be self understandable. Joomla! ACLs are tied to the user session. When you add/remove a user from user groups this does not have any effect until the user is logged out. This is why Akeeba Subscriptions checks if the user group assignment has changed due to the subscription. If this is the case the `needs_logout` flag is set. If this flag is set the user logout plugin –very unsurprisingly– logs out the user to force them to log back in so that their user privileges are set correctly. If you do not want to do that and prefer frustrating your users who just paid but do not get access to the subscriber content you can of course *disable the plugin, like you can do with any other Joomla! plugin*. I know, amazing, isn't it? Who you've known that you can actually (* gasp *) _unpublish Joomla! plugins from the Extensions, Plugins page in the back-end of Joomla!_. Oh, wow, it must take a genius to think of this! Just kidding, it's Joomla! management 101.

Therefore you know neither how Joomla! works nor how to use Joomla!. Well done, ignorant bigot boy, you suck both technically and personally.
