### ISSUE TITLE
Paypal IPN issues

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#249]
I'm wondering if someone else is experiencing issues with Paypal lately? For me 1/10 of all subscription end up with: 
akeebasubs_failure_reason     The referenced subscription ID ("custom" field) is invalid

For example I have this user that paid with paypal - in akeebasubs his subscription id is 7890, but paypal for some reason is sending the subscription id as 7889? 

Any ideas why something like this would happen?

**Comment by UWiX-nl** [comment]
Just migrated from J2.5 to J3.x and upgrade the subscriptions extension. Also getting the "referenced subscription ID ("custom" field) is invalid. :-(

Payment reports back (according to the log): completed but does not enable the subscription for the user (that states "new" for payment status).

Has something changed in the PayPal plugin or the procedure to validate the payment(s)?

**Comment by nikosdion** [comment]
Nope. I am actually using the PayPal integration on our site and it's processing the bulk of our transactions.

One thing that may not work after upgrade is existing recurring subscriptions. As I had warned in the documentation since 2011 recurring subscriptions are evil because the postback URL for subscriptions can never be modified. When the URL changes (it did with version 5) old recurring subscriptions will fail. I did try to add some support for old style postback URLs but it's not guaranteed to work. That's all we can do.

Other than that, have you tried clearing the postback URL in your PayPal settings? Since Akeeba Subscriptions 3 it's supposed to be empty and let the subscription form tell PayPal which postback URL to use.

**Comment by UWiX-nl** [comment]
Just using the standard PayPal plugin with a standard PayPal account. Nothing is changed in the setup but when checking the hidden "custom" form field before a user get's redirected to the PayPal site it's always one number lower than the actual created subscription ID.
Testing as a new user trying to subscribe to a new subscription - so recurring subscription.

The postback URL in the PayPal settings cannot be changed because that isn't available on a standard PayPal account ;-)

**Comment by compojoom** [comment]
I'm the one who posted the issue, but I don't actually remember doing that wow...
I think that the solution had nothing to do with akeeba. Now, that I think of... I spoke with  paypal and I actually they have an interface where you can resend the callbacks. In my case they were never reaching the site. So after talking to siteground and giving them the paypal ipn ips
https://developer.paypal.com/docs/classic/lifecycle/faq/#ipaddress they added them to their firewall and after that everything was working again with the IPN. Try to resend the IPNs if they are never received talk to your hosting provider and ask him to unblock the ipn servers.

**Comment by UWiX-nl** [comment]
I do not think it has anything to do with the blocking of IP addresses because last week it worked fine. But I'll also check the log files some more on the hosting server - thanks for the headsup.
The IPNs are send correctly and the logs from akeeba also show "Completed" for the transaction - but it looks like it is ot processed in the correct way.
Maybe it has something to do with othe recent upgrade from J2.5 to J3 we've done .... We're stll looking into it.

**Comment by UWiX-nl** [comment]
Just spent my morning testing in a localhost environment and it has the same result. 
The sandbox account works perfectly and the payment is handeld correctly by paypal but the site does not enable the user who bought a subscription. The status of the payment keeps resultingin "New" and not into "Confirmed".
Using 5.0.5 of Akeeba Subscriptions in Joomla! 3 (ofcourse). By the way; using Joomla 2.5 with Akeeba Subscriptions 4.1.1 (using Sandbox Paypal) does handles the PayPal confirmation correctly ;-(

**Comment by nikosdion** [comment]
Think a second. If you are in local host how do you expect PayPal to send you an IPN? To local host? Without an Internet accessible domain? Head meet desk.

**Comment by UWiX-nl** [comment]
<grin> mind your head ;-) Ofcourse, I realize that a localhost cannot receive an IPN - it was too much thinking while typing on my part.
The localhost is not the correct description of my message - it should have been "test environment". Guess I had way to less sleep last night... :-( But to be honest - at the begin stage of this issue I did use a localhost machine, until I realized.... well...

The test site used is reachable to receive an IPN - but no luck. I'll test some more and try to collect more debug information. If it's working on your end than it must be the migration to J3 which causes this issue. I'll start checking each option and configuration setting again. 
Thanks!

**Comment by nikosdion** [comment]
For what it's worth our site has been upgraded between 1.7, 2.5, 3.2 and all subsequent versions. And it does work :)

**Comment by UWiX-nl** [comment]
Well, **compojoom** it seems you we're right all allong. When my hosting provider added the IP addresses (renewed) them to their firewall whitelist the testing works correctly.

Just tested over-and-over-and-over again for the last couple of days and it drove me nuts .... Than after the remarks of **nikosdion** it started me thinkin' ... So I've started the testing all over again - step by step - elliminating everything which was not the problem. In the meanwhile I had left a help ticket at my hosting provider with a list of ip's from the link **compojoom** provided (also the sandbox ip's). 

Testing using PayPal sandbox - don't worry **nikosdion** I've used "emergency off-line" in AdminTools and allowed only the (sandbox) PayPal ip's using htaccess :grin: - which worked correctly during testing.

_Noticed one thing during testing - when you click "Cancel payment and return to webshop site" in the PayPal payment screen - the subscription still says "New" on the payment status. But that could be a normal response, though._

Anyway - I'll keep track of the process for the upcoming weeks but it seems I've found the solution. Thank you guys for the support!

**Comment by UWiX-nl** [comment]
Sadly enough - it still doesn't work. Also noticed the log file isn't filled since my last testing with the sandbox setup.
Starting to think it could be something in the htaccess file that's causing a limit. It is a htaccess fully generated by the latest AdminTools. I'll start looking into that.

**Comment by nikosdion** [comment]
As you may have noticed, we use the PayPal integration on our site. It stands to reason that we do use our own security software on our own site. As long as you've disabled the Disable PHP Easter Eggs protection and possibly the direct file inclusion prevention you should not have a problem with the PayPal integration.

**Comment by UWiX-nl** [comment]
Okay, hmmmm, the Easter Eggs settings I missed. Disabled it just yet. 
For the "possibly the direct file inclusion prevention" I'll check up with the documentation of AdminTools. Thanks again!
