### ISSUE TITLE
Paypal IPN issues

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#281]
Hey Nick,

It's a mistery why this happens to me only... 

In the paypal plugin you have this: const IPNPostbackDomain = 'www.paypal.com';
If I leave it like the iPN verification fails. The funny thing is that the ipn_failure reason is:
Unknown PayPal response. HTTP 200. Message: 

And what follows is the source code of the paypal.com site??? 

We were using const IPNPostbackDomain = 'ipnpb.paypal.com'; and that worked for some time, but since few days we now get:
Could not open connection to https://ipnpb.paypal.com, cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 110

Have you or anyone else encountered this? What postbackdomain are you using on the akeeba site?

**Comment by nikosdion** [comment]
That's due to a change PayPal has made. The IPN endpoint www.paypal.com is deprecated (but still works). The new endpoint, ipnpb.paypal.com, however requires server-side support for TLS 1.2 and SHA-256 signed SSL certificates. Please read https://devblog.paypal.com/upcoming-security-changes-notice/

During the transition period (until June 2017) the old endpoint (www) supports connections with older TLS or SSL protocol versions for postbacks while the new endpoint only accepts TLS 1.2 connections. I chose to use the old endpoint since some servers, like yours, don't support TLS 1.2. That's why you got a cURL error. You can and must fix that by asking your host to upgrade OpenSSL and recompile libcurl and the PHP cURL module against it. Please note that libcurl compiled against GnuTLS (the default in Ubuntu Server) *WILL NOT WORK WITH PAYPAL* since its implementation is broken!

I don't know why the old endpoint doesn't work for you. I would suspect that there is a caching proxy in front of your server for outbound requests. Quite naturally, that would cache the PayPal site code for the www.paypal.com domain. Again, ask your host.

AkeebaBackup.com runs an **unmodified** version of our software, always. The only thing we will ever do on our site is template overrides to provide visual customizations that cannot be generalized in a way that makes sense to other developers. Right now we have two template overrides for Akeeba Subs (presenting the list of available subscriptions) and ARS (presenting the list of available downloads), implemented as modules and custom HTML articles with plugin merge codes. We never, ever modify the actual PHP code on our site. All changes are committed back to the repository. If we need something custom we add an option.

**Comment by compojoom** [comment]
Hey Nick,
All that is in my case not true. Our server supports TLS1.2 etc. 
What seems to be the issue is that I only used this
```php
const IPNPostbackDomain = 'ipnpb.paypal.com'; 
```

and I didn't use this one:
```php
$url = 'https://' . $hostname . '/cgi-bin/webscr';
```

now when the ipnpb callback goes to /cgi-bin/websrc it works. The last callback on our site completed just fine with no error.

**Comment by nikosdion** [comment]
Apparently PayPal has _finally_ updated their documentation to clarify what we should be doing. We have to both use ipnpb.paypal.com _and_ append /cgi-bin/webscr. I have no idea why the other set of values works for me. When I had tried the new endpoint in October and again in January it didn't work. I tried again now and it works 🤷
