### ISSUE TITLE
Joomla user group

### ISSUE THREAD

**Issue by edinmark** [akeeba/akeebasubs#299]
I know Akeebasubs is now for developers only; and not general support. Nonetheless I wanted to report an experience that started occurring a couple months ago; as i dont know if this is a problem others have had. 

In my setup, users subscribe and are changed to various Joomla user groups; which controls access to content.  All worked absolutely fine, and I changed nothing on my site so far as I could tell. 

However, I started getting users reporting errors a couple months back - that although their subscription was active, they could not access content. 

Lo and behold, it was true.  A small minority of users (and I can find no obvious pattern here) have an appropriately valid subscription (and the subscription status is active on the backend, as expected); but their Joomla usergroup has been removed (as though the subscription had been expired, which it wasn't).   I sort the problem by "Running integrations" on the backend which appropriately re-assigns the user to the joomla user group. 

I have no clue what is causing this.  The subscriptions themselves are not "faulty" because they are clearly active, but the user has been removed from the Jooma Usergroup.  I can only wonder whether the plugin "Akeeba Subscriptions - Joomla! Usergroups Integration" has some conflict issue with my setup.

**Comment by nikosdion** [comment]
This happens when the plugin "Akeeba Subscriptions - Joomla! Usergroups Integration" didn't get the chance to execute when your site received the payment notification. This typically happens when sending the email fails because the email plugins have by default a lower priority than the usergroups integration plugin. As a result the system tries to send the email first, fails, crashes with an error and the usergroups integration never runs.

Solution: Go to Manage, Plugins and filter by "akeebasubs" type. Order by the plugin ordering (the first column with the two triangles icon). Drag the "Akeeba Subscriptions - Joomla! Usergroups Integration" to the top, or at least above "Akeeba Subscriptions - Emails", "Akeeba Subscriptions - Administrator Emails" and "Akeeba Subscriptions - Integrated Invoicing".

Ideally you should see why your email server craps its pants. We had an interesting issue with a hosting company a few weeks ago. They had a mistake in their configuration. If the sender didn't match a valid email on your configured domain they would enter an infinite loop instead of throwing an error. Our permanent solution was to use Amazon SES (through its SMTP endpoint) to send emails from the affected site. Never had a problem again.

**Comment by edinmark** [comment]
Thanks very much Nikos for explaining this.  I had actually read a post from you somewhere else about the ordering of plugins and my ordering was OK.   

I didnt explain properly than in my case - subscriptions are activated fine, emails are sent confirming activation and Joomla Usergroups are appropriately assigned. The user then accesses content as expected. However, here's the issue: the user is suddenly thrown out of the Joomla usergroup to which they were assigned at some date days or even weeks later despite a valid subscription. The date of the subscription says its valid, and indeed the subscription is marked as active on the back end (and no expiry emails or notices are sent) but... here's the kicker... the user has somehow been expelled from their usergroup.  No idea why. It has happened to less than 10% of subscriptions - and most seemed to have been in November or December. 

My only thoughts are: could there be a date conflict (days interpreted as months or similar) causing misfiring of usergroup plugin?  or else, maybe another action outside Akeebasubs causes Joomla to interfere with the usergroup. 

This error is clearly beyond the scope of this Github project and I appreciate your initial suggestions Nikos. If anyone comes across a similar issue i'd be grateful for advice.

**Comment by nikosdion** [comment]
Nope. A third party extension must be removing those users from their user groups. The usergroup integration plugin of Akeeba Subscriptions only fires on subscription status change events. If the subscription is still active the plugin has not been triggered.

**Comment by edinmark** [comment]
i figured that might be the most likely culprit.  i'll keep hunting and post if i find the answer for others.  take care,mark
