### ISSUE TITLE
Subscription Form Prefill -> Renewals getting harder

### ISSUE THREAD

**Issue by svenbluege** [akeeba/akeebasubs#309]
**Expected behavior**
I see my subscription data like address, email and so on.

**Current behavior**
the form is empty

**Steps to repeat**

- have a subscription and a fresh browser session
- open https://www.akeebabackup.com/subscribe/new/akeebadeluxe.html
- login
- see https://www.akeebabackup.com/subscribe/new/akeebadeluxe.html automatically

**Notes**
Seems like the first access to the page fills the cache for the form. Since I'm not logged in, there is not much to prefill. If I log in, the form cache stays the same. I'm not sure if a system plugin for resetting that cache is the right idea. What do you think?

**Comment by nikosdion** [comment]
I'm afraid that's a side-effect of how Joomla works. When you log in your session is not discarded, it is carried on and converted to a logged in session. This means that your session data carries forward and we have no way to detect that it's out of date.

"Fixing" this a few years ago introduced an even worse bug: whenever you tried to replace information displayed in the form, e.g. change your address, the _old data_ was used instead. This caused some interesting problems, from the obvious issue of invoices being wrong when any of the address / business name information was out of date, to VAT being charged erroneously when the old VAT number was no longer VIES registered while the new is and last, but not least, the email address never updating leading to lost renewals.

I have no way to fix this. In fact, this is currently the least of my worries. Between the VAT reform which makes us merchants liable for our clients lying about their tax residence(!), the need to charge the correct VAT when the EU doesn't even have a list of the exceptions upon exceptions of the regular VAT rate for services (e.g. selling services to Aghion Oros in Greece has no VAT, same with Canary Islands, Monaco has French tax even though it's a different country but Saint Martin which is the same but in the Caribbean has indeed no VAT etc etc etc), the EU consumer protection directive making us liable for the idiots who claim they didn't know what they purchases unless you have them explicitly pinky-swear they are fully conformed on the products, the GDPR which opens a whole can of worms on what the hell I am supposed to retain and for how long and the online tax reform proposal (where, if enacted, we will pay income tax to each member state much like VAT) I don't think I am interested in continuing writing Akeeba Subscriptions any more. To be honest, my plan is to look into using a hosted service such as Paddle, Avangate or SoftSpring. Because, seriously, I don't want to deal with all that crap anymore. My time costs and it's becoming a major cost component in my software - not to mention limiting the time I have available to actually develop the software I make a living from...

So, I know that you are right but I won't try to fix it. I will keep this semi-broken system for a while, until I figure out how to use a different way to sell subscriptions from our site.

**Comment by svenbluege** [comment]
I totally get your point and I'm curious about that other way of selling subscriptions. Spending time on the infrastructure instead of the products which you actually want to sell is bad.

Keeping that in mind, I'm very thankful that you still maintain Akeeba Subscription!
