### ISSUE TITLE
Missing Option - Allow collection of personal information and business registrations

### ISSUE THREAD

**Issue by StarAzure** [akeeba/akeebasubs#315]
According to documentation, Front-end option includes - **Allow collection of personal information and business registrations.**
__When enabled, Akeeba Subscriptions will ask for address information and business registration information. This information is required if you have to issue invoices or receipts to your customers. On some jurisdictions, the automatic receipt generated by, for example, PayPal is adequate......_

This option is missing and with the new GDPR rules etc, it will be beneficial to be able to use this to not collect personal info such as address.

**Comment by nikosdion** [comment]
Wrong!!!! Legal requirement trumps GDPR.

**Comment by nikosdion** [comment]
As I have written in https://www.akeebabackup.com/news/1694-gdpr-and-akeeba.html

Our subscriptions software (Akeeba Subscriptions)
Things are a bit more complicated because pretty much all of the information collected by users is personal. The invoicing information is definitely personally identifiable. However, collecting it is a requirement under the EU VAT and invoicing regulations. Since there is a legal requirement to collect it the GDPR privacy provisions are superseded, i.e. you can still collect it no matter what. This information cannot be stored encrypted because you need to be able to search through it and databases don't support searching through encrypted information.

The invoice (and credit note) body itself, however, is stored encrypted as of Akeeba Subscriptions 6.1.0 which will be released in mid-May 2018. Moreover, Akeeba Subscriptions no longer stores this information as files on disk. Whenever you ask Akeeba Subscriptions for an invoice preview or to download your invoice as a PDF it will decrypt it and send it to you. Of course this also applies to credit notes.

As a general rule, we recommend that you remove or pseudonymize the subscriptions, user records, invoices and credit notes of inactive clients. We do that on our own site as part of the automatic deletion of the user profile. You may need to keep copies elsewhere to satisfy tax laws (in which case your legal requirement supersedes the GDPR provisions to privacy).

We are deploying the new version of Akeeba Subscriptions on our site. All invoices and credit notes will be only stored encrypted. We will run a special script to encrypt all of the existing information AND we will remove the copies of the invoice PDF files from our server. Copies of the invoices will be kept for a minimum of 10 years due to legal requirements both in an encrypted Amazon S3 bucket in the EU (Frankfurt) and off-line with our accountants. Do note that the accountants are also auditors and are therefore bound to existing privacy regulations which are stricter than GDPR itself. Finally, we do not allow users to delete their user profile with us within the first 90 days after they have bought their latest subscription since a. it may not have been reported to the tax authorities / VIES / VAT Mini One Stop Shop services (legal requirement) and b. that's the maximum time period after a pruchase when a client can file a payment dispute or chargeback request (meaning that we need to keep a record of the client's information to use as proof of service provisioning in these cases). Legal requirements trump GDPR provisions in these cases. Of course after 90 days from your last purchase you can delete your user account without refund if you so wish.

Important clarification: your transactions on third party sites, e.g. the payment processing companies, is NOT deleted when your user account is deleted and is NOT included in data exports requested on our site. This information is submitted to and stored by third parties. You should contact them directly to exercise your data rights with them.
