### ISSUE TITLE
Fef page not found?

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#316]
The docs say that we need fef in order to build the component.
You will also need the following path structure inside a folder on your system

    akeebasubs This repository. We will refer to this as the MAIN directory
    buildfiles Akeeba Build Tools
    fof Framework on Framework
    fef Akeeba Front-end Framework
    translations Akeeba Translations

but the fef link that points to github is giving a 404?

**Comment by nikosdion** [comment]
It looks like my reply sent by email never made it :(

You do not need FEF to build a package. Just use `phing git -Dversion=0.0.1.a1` or a similar fake version number. If there is a version number declared, the Phing build will pull the already built FEF and FOF packages instead of having to also build their dev releases from source.
