### ISSUE TITLE
Can not turn subscription on. Can not edit subscribtion - there is no 'Save' or 'Submit' button on edit page

### ISSUE THREAD

**Issue by iqdr** [akeeba/akeebasubs#323]
Hello, dear akeebasubs developers! 
This is not pretension, but information on akeebasubs issue. 

- Can not turn subscription on.
- Can not edit the subscription.
- There is no button 'Save' (or Submit) in the subscription edit page. 

Appears in Akeeba Subscriptions v.6.1.2. 
Version v.6.0.0 has the same issue. 
Akeeba Subscriptions v.5.2.5 works well (without this issue). 

Situation:
1) User made payment for subscription (payment via Hikashop is confirmed; order status is confirmed). 
[The link to screenshot: ](https://yadi.sk/i/jsvR489yvkzl-A) 

2) Subscription for this user does appear automatically (with payment event). 
But subscription appears as 'turned off' (not enabled). 
[The link to screenshot: ](https://yadi.sk/i/HOLdFbd1g1fitg) 
And this subscription cannot be turned on in the subscriptions page. 

3) I have tried to turn 'red button' in the 'Enabled' column - no effect, no changing. 
4) I have tried to edit Subscription. The very strange 'edit page' appears. It even has NO 'Save Subscription' button or something alike. Completely can not edit Subscription. 
[The link to screenshot: ](https://yadi.sk/i/30vfwqO5lJg5Fw) 

Joomla 3.8.12  PHP 5.6 

Turn back to Akeeba Subscription version 5.2.5 - it works well. 

Sorry if I disturbing you! 
Sincerely, Ilya Kudryavtsev.

**Comment by nikosdion** [comment]
It is fairly obvious from the screenshot that you have a PHP error which prevents the page from actually appearing in full. Based on where this happens, it looks that you are using an obsolete plugin. 

In Akeeba Subscriptions 6.0 we removed a lot of dead weight (feature we no longer use) and increased the minimum required PHP version to 7.0. One of the several plugins we removed was the HikaShop integration. Since you were talking about the subscription having been paid with HikaShop I assume that's the obsolete plugin (or one of the obsolete plugins) in question.

Maybe you should try finding a different subscriptions extension?
