### ISSUE TITLE
Latest release displays you must select a user

### ISSUE THREAD

**Issue by spignataro** [akeeba/akeebasubs#327]
Latest release with asexpirationcontrol system plugin display peppered throughout the site and in the admin (not allowing admin login) "you must select a user"

**Comment by spignataro** [comment]
This problem seems to occur when the following occurs:

- Do not log in
- Go and make a purchase
- Select Paypal plugin
- Go to paypal
- Do no complete the transaction
- The tables now have empty records with a 0 for the userid. It seems to want to wait for the user to come back to update this field. Although this breaks the site for everyone else.

**Comment by nikosdion** [comment]
No, this does not happen. A user (blocked) is created _before_ we start creating the `#__akeebasubs_subscriptions` record. If creating the user fails the entire method fails _before_ creating the subscription record. Since the subscription record is a prerequisite to issuing the redirect to the payment processor what you describe cannot occur within Akeeba Subscriptions.

You can, of course, have a third party plugin either screwing up the core users table or cocking up either our table or the Akeeba Subs events. But in either case it's not something we can or should be handling.

Finally note that I'm in the process of radically changing how Akeeba Subscriptions works. It will basically be a Paddle.com integration. If you plan on using PayPal etc -- all the features of version 6 -- you need to maintain a fork if it yourself.
