### ISSUE TITLE
Spanish tax rules are (yet) bit different

### ISSUE THREAD

**Issue by jcodewalker** [akeeba/akeebasubs#384]
Hi Nicholas,
I'm sorry to say that EU vat saga is even a bit more complicated...

Except for Spain’s commitments to the European Union (“EU”) on value added tax (“VAT”), at present there is no tax regime in Spain that specifically regulates the trading of goods and services on the Internet. Therefore, the same taxes and the same rules as those for other forms of commerce apply to e-commerce. 

What does it means?
For non Eurozone residencial customer I have to apply vat to private customer while I have to not apply vat to company providing a Vat code (whatever, since there is not a check over non eu vat registration number).
Have a look here (english text version): [https://guidetobusinessinspain.com/en/7-marco-juridico-e-implicaciones-fiscales-del-comercio-electronico-en-espana/7-3-implicaciones-fiscales-en-espana-del-comercio-electronico/](https://guidetobusinessinspain.com/en/7-marco-juridico-e-implicaciones-fiscales-del-comercio-electronico-en-espana/7-3-implicaciones-fiscales-en-espana-del-comercio-electronico/)

Even with v. 6.2.2. I can't do it as Akeebasubs doesn't check company-purchase/vat-registration pair.

Any hint?
Thanks in advance.

**Comment by nikosdion** [comment]
Akeeba Subs 7 removes all invoicing and taxation features since it relies entirely on Paddle for invoicing (it's just an integration with Paddle). I'm already in the last steps of implementing AS7. Also, I have explicitly said since 5 1/2 years ago that there's no support for Akeeba Subs whatsoever and it simply implements what works for my business. 

Sorry, tough luck. You will need to find different subscriptions software.
